sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
cache:
- composer
- "$HOME/.composer/cache"
php:
- 7.0
- 7.2
env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/chiramise
    - secure: "awISs8l4MAxCO+KUOH0qoH45flDjhaLUgpu8B39rk3S1Xz2wlPIwjDkOzwbcvsGsBmajdAsb/hgIB2AhyRDpLi1cOoqWR0Z/qbqP5NwfbSn6H/hzBqW6y2LyVciCrs5BdIy80HzjML+iEAc7NIhev2DGyrQU5gn29EXU0L1zYy/kBYEe+j2kxo6A5PXIqzqNUxiKzv/IsBO92/0bWfo6ksgWxtZcgIsUt6gDJ7TNVg4EiCUv1Oy6DqU0UX1PdNkvN72zaz9WgH6iEvnceknxINRJFLNZefM3X4nACGg1xH71+T9laZY55+EEuWI+/RevrBb18q4yepNKR870DNMJKji06Obn4PNDUfk8AWjXHob8TBMKy1K/aPWN7AfHrxRzfyx3rg5PPs6EOrS8sSEEuMfM+WGnqDAWGvgqpuj/yk9TX7TRJ4xzyVe4fZVQHubqeF8IFQV8UUMw0+UY+pbhUNxvLMCcFWoCNq+9FGltW5gRV1eqvGoJ6PUfmZYfBwfB/PMvblCAuWx7dcvRGdy7EzNgw3WqZoAGirnVU23Im0TLQ1M7wCKEZymY1QrqAHD5W7RIFIUg7oBAyB9Fk8lUPhk22kHmzj+gSBMEoBy0TmU8kh+m1CHSM7i27CJMikqsAHigIWs4vVzvAgwnjuEh8vBLEPfFFs1KAZe4Iu1rCCw="
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=5.0 WP_MULTISITE=0
matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
before_script:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install v10.13.0
  - node --version
  - npm install && npm start
script:
- npm test
after_success:
- curl -L https://raw.githubusercontent.com/fumikito/wp-readme/master/wp-readme.php | php
- curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
